version: '3'

services:
  app:
    container_name: kiosk-server
    restart: always
    build:
      context: ./kiosk-server
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DATASOURCE_HOST}:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
  
  web:
    container_name: kiosk-react
    restart: always
    build:
      context: ./kiosk-react
      dockerfile: Dockerfile

  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
      - web
